version: '3.9'
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/app_db
      - |
        ROCKET_DATABASES={
          postgres={url=postgres://postgres:postgres@postgres/app_db}
        }
    ports:
      - 8000:8000
    volumes:
      - ./:/app:z

  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_db
    command: [ "postgres", "-c", "log_statement=all" ]

  redis:
    container_name: redis
    image: redis:latest
